import { PossibleOptionItem } from '../types/tourflow';

// Curated options knowledge base for popular destinations
export const CURATED_OPTIONS_CATALOG: Record<string, PossibleOptionItem[]> = {
  darjeeling: [
    {
      id: 'opt-darj-01',
      title: 'Happy Valley Tea Estate Heritage Walk & Tasting',
      category: 'leisure',
      location: 'Lebong Cart Road, Darjeeling',
      duration: '2.5 hrs',
      cost: 950,
      description: 'Guided plantation tour through 160-year-old organic tea bushes with direct tea cupping session with master blenders.',
      image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
      tags: ['Tea', 'Scenic', 'Relaxed'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-darj-02',
      title: 'Himalayan Mountaineering Institute & Everest Museum',
      category: 'heritage',
      location: 'Jawahar Parbat, Darjeeling',
      duration: '2 hrs',
      cost: 350,
      description: 'Explore historic mountaineering artifacts, Tenzing Norgay memorial, and alpine climbing gear collections.',
      image_url: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80',
      tags: ['History', 'Museum', 'Culture'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-darj-03',
      title: 'Japanese Peace Pagoda & Nipponzan Myohoji Temple',
      category: 'sightseeing',
      location: 'West Point, Jalapahar Hill',
      duration: '1.5 hrs',
      cost: 250,
      description: 'Tranquil white Buddhist stupa with 4 stone avatars of Lord Buddha and panoramic valley silence.',
      image_url: 'https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?auto=format&fit=crop&w=800&q=80',
      tags: ['Peace', 'Spiritual', 'Views'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-darj-04',
      title: 'Mirik Lake & Sumendu Lake Boating Excursion',
      category: 'adventure',
      location: 'Mirik Valley (45km from Darjeeling)',
      duration: '4.5 hrs',
      cost: 2200,
      description: 'Scenic day drive through cardamom groves and floating Shikara boating on serene Sumendu Lake.',
      image_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
      tags: ['Excursion', 'Boating', 'Nature'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-darj-05',
      title: 'Rock Garden & Chunnu Summer Falls',
      category: 'scenic',
      location: 'Chunnu Waterfall Road',
      duration: '2 hrs',
      cost: 500,
      description: 'Multi-tiered terraced waterfall garden with cascading mountain spring streams.',
      image_url: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
      tags: ['Waterfall', 'Photography', 'Garden'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-darj-06',
      title: 'Tibetan Refugee Self-Help Centre & Carpet Weaving',
      category: 'heritage',
      location: 'Hill Side, Darjeeling',
      duration: '1.5 hrs',
      cost: 300,
      description: 'Witness master artisans handcrafting authentic Tibetan rugs, thangkas, and silver prayer wheels.',
      image_url: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      tags: ['Artisans', 'Crafts', 'Handmade'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-darj-07',
      title: 'Chowrasta Bakery Crawl: Glenary’s & Keventers Brunch',
      category: 'culinary',
      location: 'Nehru Road, The Mall',
      duration: '2 hrs',
      cost: 1100,
      description: 'Warm English cinnamon buns, Darjeeling gold tea, and open rooftop terrace vistas.',
      image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      tags: ['Bakery', 'Heritage', 'Brunch'],
      walking_intensity: 'none',
    },
    {
      id: 'opt-darj-08',
      title: 'Observatory Hill & Mahakal Sacred Ridge',
      category: 'heritage',
      location: 'Observatory Hill, Darjeeling',
      duration: '1.5 hrs',
      cost: 200,
      description: 'Sacred amalgamation where Hindu priests and Buddhist lamas chant together amidst flutter of prayer flags.',
      image_url: 'https://images.unsplash.com/photo-1571401835393-8c5f35328320?auto=format&fit=crop&w=800&q=80',
      tags: ['Spiritual', 'Views', 'Heritage'],
      walking_intensity: 'moderate',
    },
  ],

  manali: [
    {
      id: 'opt-manali-01',
      title: 'Naggar Castle & Nicholas Roerich Art Gallery',
      category: 'heritage',
      location: 'Naggar Estate, Left Bank, Manali',
      duration: '3 hrs',
      cost: 850,
      description: '15th-century wood-and-stone Himalayan castle with panoramic Beas river valley views and Roerich paintings.',
      image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
      tags: ['Heritage', 'Art', 'Views'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-manali-02',
      title: 'Vashisht Natural Sulphur Hot Springs & Vedic Temple',
      category: 'leisure',
      location: 'Vashisht Village, Manali',
      duration: '2 hrs',
      cost: 300,
      description: 'Rejuvenating geothermal mineral baths overlooking snow-clad Pir Panjal ridges.',
      image_url: 'https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?auto=format&fit=crop&w=800&q=80',
      tags: ['Hot Springs', 'Relaxation', 'Wellness'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-manali-03',
      title: 'Beas River White-Water Rafting Expedition',
      category: 'adventure',
      location: 'Babeli / Pirdi, Beas River',
      duration: '2.5 hrs',
      cost: 1600,
      description: 'Exciting Grade II-III rapids navigation with certified river safety marshals and equipment.',
      image_url: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?auto=format&fit=crop&w=800&q=80',
      tags: ['Rafting', 'Water Sports', 'Adrenaline'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-manali-04',
      title: 'Old Manali Bohemian Apple Orchard Cafe Hop',
      category: 'culinary',
      location: 'Old Manali Village & Manu Temple Road',
      duration: '2.5 hrs',
      cost: 950,
      description: 'Artisan wood-fired trout pizza, spiced apple crumble, and live acoustic music by mountain streams.',
      image_url: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80',
      tags: ['Food', 'Cafes', 'Vibes'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-manali-05',
      title: 'Jogini Waterfall Pine Forest Trail',
      category: 'scenic',
      location: 'Vashisht - Jogini Trail, Manali',
      duration: '2.5 hrs',
      cost: 400,
      description: 'Scenic forest walk ending at towering mountain cascading waterfall with misty rainbow views.',
      image_url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      tags: ['Hike', 'Waterfall', 'Forest'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-manali-06',
      title: 'Solang Valley Paragliding & Quad Biking',
      category: 'adventure',
      location: 'Solang Valley (14km from Manali)',
      duration: '3.5 hrs',
      cost: 3200,
      description: 'High-altitude tandem paragliding glide above pine glades with snow-peak backdrop.',
      image_url: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=800&q=80',
      tags: ['Paragliding', 'Adventure', 'Snow'],
      walking_intensity: 'moderate',
    },
  ],

  puri: [
    {
      id: 'opt-puri-01',
      title: 'Konark Sun Temple UNESCO World Heritage Tour',
      category: 'heritage',
      location: 'Konark, Marine Drive (35km from Puri)',
      duration: '3.5 hrs',
      cost: 1200,
      description: '13th-century colossal stone chariot architectural masterpiece with 24 carved wheels dedicated to Surya.',
      image_url: 'https://images.unsplash.com/photo-1609137144822-4a00e572074f?auto=format&fit=crop&w=800&q=80',
      tags: ['UNESCO', 'Architecture', 'Heritage'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-puri-02',
      title: 'Chilika Lake Irrawaddy Dolphin Boat Safari',
      category: 'adventure',
      location: 'Satapada, Chilika Lagoon',
      duration: '4.5 hrs',
      cost: 2400,
      description: 'Motorboat cruise across Asia’s largest brackish lagoon to spot rare playful Irrawaddy dolphins and migratory birds.',
      image_url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
      tags: ['Wildlife', 'Boating', 'Lagoon'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-puri-03',
      title: 'Raghurajpur Heritage Craft & Pattachitra Village',
      category: 'heritage',
      location: 'Raghurajpur Heritage Lane, Puri',
      duration: '2.5 hrs',
      cost: 700,
      description: 'Meet award-winning master artisans painting palm-leaf manuscripts, wood carvings, and Gotipua dancers.',
      image_url: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      tags: ['Artisans', 'Crafts', 'Heritage'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-puri-04',
      title: 'Golden Beach Eco-Retreat & Sunset Promenade',
      category: 'leisure',
      location: 'Puri Blue Flag Beach',
      duration: '2 hrs',
      cost: 350,
      description: 'Blue Flag certified pristine coastal stretch with gentle ocean breeze, lifeguards, and seaside cafe shacks.',
      image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      tags: ['Beach', 'Sunset', 'Relaxation'],
      walking_intensity: 'none',
    },
    {
      id: 'opt-puri-05',
      title: 'Shree Jagannath Ananda Bazar Mahaprasad Experience',
      category: 'culinary',
      location: 'Shree Jagannath Temple Precinct, Puri',
      duration: '2 hrs',
      cost: 450,
      description: 'Taste the sacred 56-dish Chhappan Bhog earthen-pot delicacy cooked on woodfire in the world’s largest kitchen.',
      image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
      tags: ['Spiritual', 'Prasad', 'Food'],
      walking_intensity: 'moderate',
    },
  ],

  goa: [
    {
      id: 'opt-goa-01',
      title: 'Fort Aguada & 1864 Portuguese Lighthouse',
      category: 'heritage',
      location: 'Sinquerim, Candolim, North Goa',
      duration: '2 hrs',
      cost: 400,
      description: '17th-century Portuguese fortress overlooking Arabian Sea with panoramic coastal bastion views.',
      image_url: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      tags: ['Fort', 'Views', 'Heritage'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-goa-02',
      title: 'Dudhsagar 4x4 Jeep Waterfall Jungle Safari',
      category: 'adventure',
      location: 'Bhagwan Mahavir Wildlife Sanctuary, Sonaulim',
      duration: '5 hrs',
      cost: 2800,
      description: 'Thrilling off-road safari through dense Western Ghats jungle streams to the thunderous 310m four-tiered waterfall.',
      image_url: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80',
      tags: ['Waterfall', 'Safari', 'Western Ghats'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-goa-03',
      title: 'Fontainhas Latin Quarter Heritage Photo Walk',
      category: 'heritage',
      location: 'Fontainhas, Panaji, Goa',
      duration: '2 hrs',
      cost: 650,
      description: 'Stroll past pastel yellow and cobalt blue Portuguese villas, ornate tiled balconies, and indie bakeries.',
      image_url: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=800&q=80',
      tags: ['Photography', 'Architecture', 'Culture'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-goa-04',
      title: 'Baga & Calangute Watersports: Parasailing & Jet Skiing',
      category: 'adventure',
      location: 'Baga Beach, North Goa',
      duration: '2.5 hrs',
      cost: 2200,
      description: 'Tandem parasailing above the azure sea with bumper rides, banana boats, and speed watercraft thrills.',
      image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      tags: ['Parasailing', 'Watersports', 'Beach'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-goa-05',
      title: 'Basilica of Bom Jesus & Old Goa UNESCO Churches',
      category: 'heritage',
      location: 'Old Goa (Velha Goa)',
      duration: '2 hrs',
      cost: 300,
      description: 'UNESCO Baroque cathedral housing the sacred relics of St. Francis Xavier and Se Cathedral.',
      image_url: 'https://images.unsplash.com/photo-1580227974546-f9479b183669?auto=format&fit=crop&w=800&q=80',
      tags: ['UNESCO', 'Churches', 'History'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-goa-06',
      title: 'Sahakari Spice Plantation Guided Tour & Goan Buffet',
      category: 'culinary',
      location: 'Ponda, Central Goa',
      duration: '3 hrs',
      cost: 950,
      description: 'Aromatic walk through vanilla, cardamom, and betel nut groves followed by traditional Goan fish curry and feni tasting.',
      image_url: 'https://images.unsplash.com/photo-1587922546307-776227941871?auto=format&fit=crop&w=800&q=80',
      tags: ['Spices', 'Buffet', 'Nature'],
      walking_intensity: 'light',
    },
  ],

  kerala: [
    {
      id: 'opt-ker-01',
      title: 'Alleppey Backwaters Houseboat Day Cruise & Kerala Feast',
      category: 'leisure',
      location: 'Punnamada Jetty, Alleppey (Alappuzha)',
      duration: '5 hrs',
      cost: 3500,
      description: 'Glide along coconut-canopied canals in a private thatched Kettuvallam with fresh Karimeen fish fry served on banana leaf.',
      image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
      tags: ['Backwaters', 'Houseboat', 'Feast'],
      walking_intensity: 'none',
    },
    {
      id: 'opt-ker-02',
      title: 'Munnar Kolukkumalai Sunrise 4x4 Jeep Safari',
      category: 'adventure',
      location: 'Kolukkumalai Estate, Munnar',
      duration: '4 hrs',
      cost: 2400,
      description: 'Early morning bumpy off-road drive to the world’s highest organic tea plantation (7,900ft) for panoramic cloud-bed sunrise.',
      image_url: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      tags: ['Sunrise', 'Tea Estate', 'Off-road'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-ker-03',
      title: 'Fort Kochi Chinese Fishing Nets & Kathakali Night',
      category: 'heritage',
      location: 'Fort Kochi Heritage Quarter',
      duration: '2.5 hrs',
      cost: 850,
      description: 'Sunset stroll by cantilevered maritime nets followed by classical Kathakali facial makeup demonstration and dance drama.',
      image_url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80',
      tags: ['Kathakali', 'Culture', 'Fishing Nets'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-ker-04',
      title: 'Periyar Wildlife Sanctuary Bamboo Rafting & Jungle Walk',
      category: 'adventure',
      location: 'Thekkady, Periyar Tiger Reserve',
      duration: '4.5 hrs',
      cost: 2600,
      description: 'Eco-guided bamboo rafting across Periyar lake to spot wild elephants, bison, and exotic hornbills.',
      image_url: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      tags: ['Wildlife', 'Rafting', 'Sanctuary'],
      walking_intensity: 'moderate',
    },
  ],

  kashmir: [
    {
      id: 'opt-kash-01',
      title: 'Dal Lake Sunset Shikara Ride to Floating Market & Char Chinar',
      category: 'leisure',
      location: 'Ghat No. 1 to Char Chinar, Srinagar',
      duration: '2.5 hrs',
      cost: 1200,
      description: 'Relax on upholstered Kashmiri daybeds gliding through water lilies, floating vegetable gardens, and willow canals.',
      image_url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
      tags: ['Shikara', 'Dal Lake', 'Sunset'],
      walking_intensity: 'none',
    },
    {
      id: 'opt-kash-02',
      title: 'Gulmarg Kongdori Gondola Cable Car (Phase 1 & 2)',
      category: 'adventure',
      location: 'Gulmarg Gondola Base Station, Gulmarg',
      duration: '3.5 hrs',
      cost: 2100,
      description: 'Ascend to 13,780ft at Apharwat Peak on one of Asia’s highest cable cars with year-round snow and ski bowls.',
      image_url: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80',
      tags: ['Gondola', 'Snow', 'Peaks'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-kash-03',
      title: 'Pahalgam Betaab & Aru Valley Pony Trek',
      category: 'scenic',
      location: 'Betaab Valley & Lidder River Valley',
      duration: '4 hrs',
      cost: 1800,
      description: 'Lush alpine meadows surrounded by snow-dusted fir forests along the roaring azure Lidder River.',
      image_url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
      tags: ['Valleys', 'River', 'Pony Trail'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-kash-04',
      title: 'Mughal Gardens: Nishat Bagh & Shalimar Bagh Heritage Walk',
      category: 'heritage',
      location: 'Boulevard Road, Srinagar',
      duration: '2.5 hrs',
      cost: 500,
      description: 'Terraced Persian-style pleasure gardens with cascading fountains, chinar trees, and Zabarwan mountain views.',
      image_url: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80',
      tags: ['Gardens', 'Mughal', 'Fountains'],
      walking_intensity: 'light',
    },
  ],

  rajasthan: [
    {
      id: 'opt-raj-01',
      title: 'Amber Fort Elephant Ramparts & Sheesh Mahal Mirror Palace',
      category: 'heritage',
      location: 'Devisinghpura, Amer, Jaipur',
      duration: '3 hrs',
      cost: 1100,
      description: 'Hilltop Rajput fort with intricate marble courtyards, Maota Lake reflections, and opulent glass mirror mosaics.',
      image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
      tags: ['Fort', 'Palace', 'Heritage'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-raj-02',
      title: 'Lake Pichola Royal Sunset Boat Cruise to Jag Mandir',
      category: 'leisure',
      location: 'Rameshwar Ghat, City Palace, Udaipur',
      duration: '2 hrs',
      cost: 1400,
      description: 'Scenic motorboat sail past Lake Palace and ghats to the island palace garden with Aravalli mountain views.',
      image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      tags: ['Lake', 'Sunset', 'Udaipur'],
      walking_intensity: 'none',
    },
    {
      id: 'opt-raj-03',
      title: 'Jaisalmer Sam Sand Dunes Sunset Camel Safari & Folk Dance',
      category: 'adventure',
      location: 'Sam Sand Dunes, Thar Desert, Jaisalmer',
      duration: '4 hrs',
      cost: 2200,
      description: 'Camel trek across rippling golden desert dunes followed by Kalbelia folk dance around bonfire with Rajasthani thali.',
      image_url: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
      tags: ['Desert', 'Camel Safari', 'Folk Dance'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-raj-04',
      title: 'Mehrangarh Fort Flying Fox Zip-line & Museum',
      category: 'adventure',
      location: 'Fort Road, Jodhpur',
      duration: '2.5 hrs',
      cost: 1900,
      description: 'Glide over desert lakes and ramparts with bird’s-eye vistas of the Blue City below.',
      image_url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      tags: ['Zipline', 'Blue City', 'Mehrangarh'],
      walking_intensity: 'moderate',
    },
  ],

  bali: [
    {
      id: 'opt-bali-01',
      title: 'Ubud Sacred Monkey Forest & Tegallalang Rice Terrace Swing',
      category: 'scenic',
      location: 'Padangtegal & Tegallalang, Ubud',
      duration: '4 hrs',
      cost: 1600,
      description: 'Ancient mossy banyan temple sanctuary with playful macaques followed by adrenaline soaring swing over emerald paddy tiers.',
      image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
      tags: ['Rice Terraces', 'Swing', 'Monkeys'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-bali-02',
      title: 'Uluwatu Cliff Temple & Sunset Kecak Fire Dance',
      category: 'heritage',
      location: 'Pecatu, South Kuta, Badung',
      duration: '3 hrs',
      cost: 1800,
      description: 'Spectacular 70m limestone sea cliff temple amphitheater with rhythmic 50-man chanting chorus against crashing ocean waves.',
      image_url: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80',
      tags: ['Kecak', 'Fire Dance', 'Cliffs'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-bali-03',
      title: 'Mount Batur Volcano Sunrise Trek & Natural Hot Springs',
      category: 'adventure',
      location: 'Kintamani, Bangli Regency',
      duration: '6 hrs',
      cost: 3200,
      description: 'Early morning caldera climb to 1,717m peak for sunrise above the clouds, steam vent breakfast, and geothermal lakeside baths.',
      image_url: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80',
      tags: ['Volcano', 'Sunrise', 'Trek'],
      walking_intensity: 'high',
    },
  ],

  london: [
    {
      id: 'opt-lon-01',
      title: 'Tower of London & Crown Jewels Guided Tour',
      category: 'heritage',
      location: 'Tower Hill, London EC3N 4AB',
      duration: '3 hrs',
      cost: 3200,
      description: 'Historic royal fortress, Yeoman Warder Beefeater tours, and viewing the glittering 23,000 gemstone Crown Jewels.',
      image_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
      tags: ['Crown Jewels', 'UNESCO', 'History'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-lon-02',
      title: 'Westminster Abbey & Parliament Big Ben Walk',
      category: 'heritage',
      location: 'Dean’s Yard, Westminster, London',
      duration: '2.5 hrs',
      cost: 2600,
      description: 'Royal coronation church of British monarchs since 1066 with Poets’ Corner and iconic Elizabeth Tower views.',
      image_url: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=800&q=80',
      tags: ['Abbey', 'Big Ben', 'Westminster'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-lon-03',
      title: 'Thames Clipper Twilight Cruise & Borough Market Food Trail',
      category: 'culinary',
      location: 'London Bridge & Borough High St',
      duration: '3 hrs',
      cost: 1800,
      description: 'River skyline cruise to Tower Bridge followed by artisan cheeses, scotch eggs, and salt beef bagels at Britain’s oldest food market.',
      image_url: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?auto=format&fit=crop&w=800&q=80',
      tags: ['Borough Market', 'River Cruise', 'Food'],
      walking_intensity: 'light',
    },
  ],

  'uttar pradesh': [
    {
      id: 'opt-up-01',
      title: 'Taj Mahal Dawn Sunrise Guided VIP Tour',
      category: 'heritage',
      location: 'Dharmapuri, Forest Colony, Tajganj, Agra',
      duration: '3 hrs',
      cost: 1200,
      description: 'Witness the iconic white marble wonder of the world illuminated by soft golden morning rays with reflections on the Yamuna.',
      image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
      tags: ['Taj Mahal', 'UNESCO', 'Sunrise'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-up-02',
      title: 'Dashashwamedh Ghat Evening Ganga Aarti Boat Experience',
      category: 'heritage',
      location: 'Dashashwamedh Ghat, Varanasi',
      duration: '2.5 hrs',
      cost: 850,
      description: 'Grand choreography of priests holding brass fire lamps with conch blowing, Vedic chants, and floating marigold diyas on the Ganges.',
      image_url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
      tags: ['Ganga Aarti', 'Spiritual', 'Boat Ride'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-up-03',
      title: 'Kashi Vishwanath Golden Temple Corridor & Sarnath Stupa',
      category: 'heritage',
      location: 'Vishwanath Gali, Varanasi & Sarnath Deer Park',
      duration: '3.5 hrs',
      cost: 650,
      description: 'Historic Jyotirlinga river corridor followed by Sarnath where Lord Buddha delivered his First Sermon (Dharmachakra).',
      image_url: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      tags: ['Kashi', 'Sarnath', 'Buddhism'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-up-04',
      title: 'Agra Fort & Diwan-i-Khas Royal Mughal Palaces',
      category: 'heritage',
      location: 'Agra Fort, Rakabganj, Agra',
      duration: '2.5 hrs',
      cost: 600,
      description: 'Massive 16th-century red sandstone fortress palace complex where Emperor Shah Jahan spent his final years overlooking the Taj.',
      image_url: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
      tags: ['Mughal', 'Agra Fort', 'History'],
      walking_intensity: 'moderate',
    },
  ],

  shimla: [
    {
      id: 'opt-shm-01',
      title: 'The Ridge, Mall Road & Christ Church Colonial Walk',
      category: 'heritage',
      location: 'The Ridge, Central Shimla',
      duration: '2.5 hrs',
      cost: 450,
      description: 'Heritage stroll through neo-Gothic 1857 Christ Church, Gaiety Theatre, and Lakkar Bazaar wooden craft stalls.',
      image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
      tags: ['Heritage', 'Mall Road', 'Colonial'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-shm-02',
      title: 'Jakhoo Hill Hanuman Temple Aerial Ropeway',
      category: 'sightseeing',
      location: 'Jakhoo Temple, Highest Peak of Shimla (8,050ft)',
      duration: '2 hrs',
      cost: 650,
      description: 'Scenic glass cable car ascent to the towering 108ft vermilion Lord Hanuman statue with panoramic Himalayan views.',
      image_url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      tags: ['Ropeway', 'Temple', 'Panoramas'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-shm-03',
      title: 'Kufri Alpine Snow Viewpoint & Nature Park Trail',
      category: 'adventure',
      location: 'Kufri (16km from Shimla)',
      duration: '4 hrs',
      cost: 1600,
      description: 'High-altitude pine glades with horse riding trails, Himalayan monal pheasant sightings, and snow tobogganing.',
      image_url: 'https://images.unsplash.com/photo-1578894381163-e72c17f2d45f?auto=format&fit=crop&w=800&q=80',
      tags: ['Kufri', 'Snow', 'Horses'],
      walking_intensity: 'moderate',
    },
  ],

  ladakh: [
    {
      id: 'opt-lad-01',
      title: 'Pangong Tso High-Altitude Azure Lake Expedition',
      category: 'scenic',
      location: 'Pangong Tso (14,270ft), Changthang Plateau',
      duration: '6 hrs',
      cost: 3600,
      description: 'Witness the iconic 134km endorheic lake changing shades from deep turquoise to cobalt blue against barren brown mountains.',
      image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
      tags: ['Pangong', 'Lake', 'High Altitude'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-lad-02',
      title: 'Nubra Valley Hunder Sand Dunes & Double-Humped Camel Safari',
      category: 'adventure',
      location: 'Hunder Desert, Nubra Valley',
      duration: '5 hrs',
      cost: 2800,
      description: 'Ride rare furry Bactrian camels along white sand dunes nestled between snow-capped Karakoram peaks.',
      image_url: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      tags: ['Nubra', 'Camels', 'Dunes'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-lad-03',
      title: 'Thiksey Monastery Morning Chanting & Indus Sangam Confluence',
      category: 'heritage',
      location: 'Thiksey & Nimmu, Leh',
      duration: '3.5 hrs',
      cost: 950,
      description: '12-story whitewashed gompa resembling the Potala Palace with 49ft Maitreya Buddha statue and conch shell prayer ceremonies.',
      image_url: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
      tags: ['Monastery', 'Chanting', 'Sangam'],
      walking_intensity: 'moderate',
    },
  ],

  rishikesh: [
    {
      id: 'opt-rish-01',
      title: 'Ganga White-Water Rafting (Marine Drive to Shivpuri)',
      category: 'adventure',
      location: 'Marine Drive - Shivpuri Stretch, Rishikesh',
      duration: '3 hrs',
      cost: 1600,
      description: 'Navigate thrilling Grade III-IV rapids like Three Blind Mice, Roller Coaster, and Golf Course with cliff jumping stops.',
      image_url: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?auto=format&fit=crop&w=800&q=80',
      tags: ['Rafting', 'Ganges', 'Rapids'],
      walking_intensity: 'moderate',
    },
    {
      id: 'opt-rish-02',
      title: 'Triveni Ghat Evening Maha Aarti & Floating Diya Ceremony',
      category: 'heritage',
      location: 'Triveni Ghat, Mayakund, Rishikesh',
      duration: '2 hrs',
      cost: 400,
      description: 'Spiritual dusk gathering at the confluence of Ganga, Yamuna, and Saraswati with rhythmic drums, bells, and floating lamps.',
      image_url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80',
      tags: ['Ganga Aarti', 'Spiritual', 'Triveni'],
      walking_intensity: 'light',
    },
    {
      id: 'opt-rish-03',
      title: 'Beatles Ashram (Chaurasi Kutia) Meditation & Graffiti Walk',
      category: 'heritage',
      location: 'Swarg Ashram, Rishikesh',
      duration: '2.5 hrs',
      cost: 650,
      description: 'Historic 1968 retreat where The Beatles wrote the White Album with psychedelic graffiti murals and meditation stone domes.',
      image_url: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      tags: ['Beatles', 'Ashram', 'Art'],
      walking_intensity: 'moderate',
    },
  ],
};

// Aliases and synonym mapping to ensure any variation maps to the right destination
const DESTINATION_ALIASES: Record<string, string> = {
  // Goa
  goa: 'goa',
  'north goa': 'goa',
  'south goa': 'goa',
  panaji: 'goa',
  panjim: 'goa',
  candolim: 'goa',
  calangute: 'goa',
  baga: 'goa',
  anjuna: 'goa',
  vagator: 'goa',
  morjim: 'goa',
  palolem: 'goa',
  colva: 'goa',
  dudhsagar: 'goa',

  // Darjeeling
  darjeeling: 'darjeeling',
  darj: 'darjeeling',
  mirik: 'darjeeling',
  kurseong: 'darjeeling',
  ghoom: 'darjeeling',
  lebong: 'darjeeling',

  // Manali
  manali: 'manali',
  kullu: 'manali',
  solang: 'manali',
  vashisht: 'manali',
  naggar: 'manali',
  sissu: 'manali',
  rohtang: 'manali',
  atal: 'manali',

  // Puri / Odisha
  puri: 'puri',
  'jagannath puri': 'puri',
  odisha: 'puri',
  orissa: 'puri',
  konark: 'puri',
  chilika: 'puri',
  satapada: 'puri',
  raghurajpur: 'puri',
  bhubaneswar: 'puri',

  // Kerala
  kerala: 'kerala',
  munnar: 'kerala',
  alleppey: 'kerala',
  alappuzha: 'kerala',
  kochi: 'kerala',
  cochin: 'kerala',
  thekkady: 'kerala',
  wayanad: 'kerala',
  varkala: 'kerala',
  kovalam: 'kerala',
  kumarakom: 'kerala',

  // Kashmir
  kashmir: 'kashmir',
  srinagar: 'kashmir',
  gulmarg: 'kashmir',
  pahalgam: 'kashmir',
  sonamarg: 'kashmir',
  'jammu & kashmir': 'kashmir',
  doodhpathri: 'kashmir',

  // Rajasthan
  rajasthan: 'rajasthan',
  jaipur: 'rajasthan',
  udaipur: 'rajasthan',
  jodhpur: 'rajasthan',
  jaisalmer: 'rajasthan',
  pushkar: 'rajasthan',
  bikaner: 'rajasthan',
  ajmer: 'rajasthan',

  // Bali
  bali: 'bali',
  ubud: 'bali',
  seminyak: 'bali',
  canggu: 'bali',
  kuta: 'bali',
  uluwatu: 'bali',
  kintamani: 'bali',
  'nusa penida': 'bali',
  denpasar: 'bali',
  sanur: 'bali',

  // London
  london: 'london',
  westminster: 'london',
  greenwich: 'london',
  uk: 'london',
  england: 'london',

  // Uttar Pradesh
  'uttar pradesh': 'uttar pradesh',
  up: 'uttar pradesh',
  varanasi: 'uttar pradesh',
  banaras: 'uttar pradesh',
  kashi: 'uttar pradesh',
  agra: 'uttar pradesh',
  lucknow: 'uttar pradesh',
  ayodhya: 'uttar pradesh',
  mathura: 'uttar pradesh',
  vrindavan: 'uttar pradesh',
  sarnath: 'uttar pradesh',

  // Shimla
  shimla: 'shimla',
  kufri: 'shimla',
  chail: 'shimla',
  mashobra: 'shimla',
  narkanda: 'shimla',

  // Ladakh
  ladakh: 'ladakh',
  leh: 'ladakh',
  pangong: 'ladakh',
  nubra: 'ladakh',
  zanskar: 'ladakh',
  khardungla: 'ladakh',
  hunder: 'ladakh',

  // Rishikesh
  rishikesh: 'rishikesh',
  haridwar: 'rishikesh',
  uttarakhand: 'rishikesh',
  mussoorie: 'rishikesh',
  nainital: 'rishikesh',
  dehradun: 'rishikesh',
};

/**
 * Normalizes user destination input and matches against curated options
 */
export function matchDestinationKey(rawDestination: string): string | null {
  if (!rawDestination) return null;
  const clean = rawDestination
    .toLowerCase()
    .replace(/^(trip to|travel to|explore|visit|tour to|vacation in|plan for)\s+/i, '')
    .trim();

  // 1. Direct alias check
  if (DESTINATION_ALIASES[clean]) {
    return DESTINATION_ALIASES[clean];
  }

  // 2. Substring matching against known aliases
  for (const [alias, canonicalKey] of Object.entries(DESTINATION_ALIASES)) {
    if (clean.includes(alias) || alias.includes(clean)) {
      return canonicalKey;
    }
  }

  // 3. Word token matching
  const tokens = clean.split(/[\s,–-]+/).filter((t) => t.length > 2);
  for (const token of tokens) {
    if (DESTINATION_ALIASES[token]) {
      return DESTINATION_ALIASES[token];
    }
  }

  return null;
}

/**
 * Procedural authentic fallback generator for ANY novel or custom destination
 */
export function generateProceduralOptions(destinationName: string): PossibleOptionItem[] {
  const cleanName = destinationName.trim().split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');

  return [
    {
      id: `opt-dyn-01-${Date.now()}`,
      title: `${cleanName} Heritage Old Town & Artisan Market Walk`,
      category: 'heritage',
      location: `Old Heritage Quarter, ${cleanName}`,
      duration: '2.5 hrs',
      cost: 750,
      description: `Guided cultural walking tour exploring historic monuments, regional architecture, and master craftsman workshops in ${cleanName}.`,
      image_url: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      tags: ['Heritage', 'Culture', 'Walk'],
      walking_intensity: 'light',
    },
    {
      id: `opt-dyn-02-${Date.now()}`,
      title: `${cleanName} Sunset Ridge & Panoramic Viewpoint Trail`,
      category: 'scenic',
      location: `Sunset Lookout Ridge, ${cleanName}`,
      duration: '2 hrs',
      cost: 350,
      description: `Unwind with sweeping 360-degree sunset panoramas across the mountains, coastline, and skyline of ${cleanName}.`,
      image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
      tags: ['Sunset', 'Panoramas', 'Photography'],
      walking_intensity: 'light',
    },
    {
      id: `opt-dyn-03-${Date.now()}`,
      title: `${cleanName} Regional Flavors & Street Food Culinary Safari`,
      category: 'culinary',
      location: `Central Bazaar, ${cleanName}`,
      duration: '2 hrs',
      cost: 900,
      description: `Savor handpicked culinary specialties, authentic street delicacies, and heritage sweets famous in ${cleanName}.`,
      image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      tags: ['Food', 'Street Food', 'Tasting'],
      walking_intensity: 'light',
    },
    {
      id: `opt-dyn-04-${Date.now()}`,
      title: `${cleanName} Nature Sanctuary & Botanical Trail Excursion`,
      category: 'adventure',
      location: `Eco Nature Reserve, ${cleanName}`,
      duration: '3.5 hrs',
      cost: 1600,
      description: `Discover pristine lush flora, native bird species, and tranquil cascades on an eco-guided trek around ${cleanName}.`,
      image_url: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=800&q=80',
      tags: ['Nature', 'Trek', 'Wildlife'],
      walking_intensity: 'moderate',
    },
    {
      id: `opt-dyn-05-${Date.now()}`,
      title: `${cleanName} Iconic Landmark & Museum Discovery Tour`,
      category: 'sightseeing',
      location: `Civic Centre, ${cleanName}`,
      duration: '2 hrs',
      cost: 500,
      description: `Skip-the-line entry to ${cleanName}’s most celebrated monument and historic artifacts gallery.`,
      image_url: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80',
      tags: ['Sightseeing', 'Landmark', 'History'],
      walking_intensity: 'light',
    },
  ];
}

/**
 * Gets options for a destination by matching canonical catalog or generating dynamic procedural options
 */
export function getPossibleOptionsForDestination(rawDestination: string): PossibleOptionItem[] {
  const matchedKey = matchDestinationKey(rawDestination);
  if (matchedKey && CURATED_OPTIONS_CATALOG[matchedKey]) {
    return CURATED_OPTIONS_CATALOG[matchedKey];
  }

  // If no static catalog exists, generate tailored procedural options for that specific destination
  return generateProceduralOptions(rawDestination || 'Darjeeling');
}
