import { Trip, Destination } from '../types/tourflow';

export function createCanonicalSeedTrips(destinationsCatalog: Destination[]): Trip[] {
  const manaliDest = destinationsCatalog.find((d) => d.slug.includes('manali')) || destinationsCatalog[0];
  const goaDest = destinationsCatalog.find((d) => d.slug.includes('goa')) || destinationsCatalog[1] || destinationsCatalog[0];
  const darjeelingDest = destinationsCatalog.find((d) => d.slug.includes('darjeeling')) || destinationsCatalog[2] || destinationsCatalog[0];

  const mainManaliTrip: Trip = {
    id: '1024',
    user_id: 'usr-rohan-sharma-001',
    destination_id: manaliDest.id,
    title: 'Manali Alpine Adventure & Solang Valley Experience',
    status: 'ongoing',
    origin: 'Mumbai',
    start_date: '2026-09-21',
    end_date: '2026-09-26',
    formatted_dates: 'Sep 21, 2026 – Sep 26, 2026',
    is_dates_confirmed: true,
    duration_days: 5,
    total_budget: 190000,
    total_cost: 186400,
    currency: 'INR',
    traveler_count: 4,
    travel_type: 'friends',
    pace: 'balanced',
    created_at: '2026-09-18T10:00:00Z',
    updated_at: new Date().toISOString(),
    destination: manaliDest,
    preferences: {
      id: 'pref-1024',
      trip_id: '1024',
      budget_tier: 'luxury',
      interests: ['adventure', 'mountains', 'snow', 'artisan_cafes', 'nature'],
      travel_companions: 'friends',
      accommodation_types: ['boutique', 'luxury'],
      transport_preferences: ['flight', 'private_suv'],
      dietary_requirements: ['vegetarian', 'vegan_friendly'],
      special_requests: 'High-adrenaline adventure activities, scenic photo points, and verified mountain chauffeurs.',
      created_at: '2026-09-18T10:00:00Z',
      updated_at: '2026-09-18T10:00:00Z',
    },
    cost_breakdown: {
      transport: 58400,
      accommodation: 92000,
      activities: 29000,
      food_and_other: 7000,
      total: 186400,
      target_budget: 190000,
      remaining_budget: 3600,
      is_under_budget: true,
    },
    itinerary: [
      // Day 1
      {
        id: 'iti-1024-d1-1',
        trip_id: '1024',
        day_number: 1,
        order_index: 1,
        item_type: 'transport',
        title: 'IndiGo Flight 6E-512 (Mumbai BOM → Chandigarh IXC)',
        description: 'Morning flight for 4 passengers with priority check-in and luggage allowance.',
        start_time: '06:30 AM',
        end_time: '09:00 AM',
        cost: 36000,
        status: 'confirmed',
        location: 'Mumbai to Chandigarh',
      },
      {
        id: 'iti-1024-d1-2',
        trip_id: '1024',
        day_number: 1,
        order_index: 2,
        item_type: 'transport',
        title: 'Private Fortuner 4x4 Chauffeur Transfer (Chandigarh → Manali)',
        description: 'Scenic journey through Bilaspur, Mandi, and the Kullu Valley with experienced mountain chauffeur.',
        start_time: '09:30 AM',
        end_time: '05:00 PM',
        cost: 14000,
        status: 'confirmed',
        location: 'Chandigarh to Manali',
      },
      {
        id: 'iti-1024-d1-3',
        trip_id: '1024',
        day_number: 1,
        order_index: 3,
        item_type: 'hotel',
        title: 'Check-in: The Himalayan Luxury Castle Resort & Spa',
        description: '2 Interconnected Victorian Chambers with private mountain balconies and fireplace.',
        start_time: '05:30 PM',
        end_time: '07:30 PM',
        cost: 23000,
        status: 'confirmed',
        location: 'Hadimba Road, Manali',
      },
      // Day 2
      {
        id: 'iti-1024-d2-1',
        trip_id: '1024',
        day_number: 2,
        order_index: 1,
        item_type: 'activity',
        title: 'Hadimba Devi Cedar Forest & Vashisht Ancient Hot Springs',
        description: 'Guided morning walk under towering Deodar cedars followed by therapeutic natural sulphur springs.',
        start_time: '09:30 AM',
        end_time: '12:30 PM',
        cost: 2400,
        status: 'confirmed',
        location: 'Dhungri / Vashisht, Manali',
      },
      {
        id: 'iti-1024-d2-2',
        trip_id: '1024',
        day_number: 2,
        order_index: 2,
        item_type: 'activity',
        title: 'Rohtang Pass & Atal Tunnel High Altitude Snow Point Expedition',
        description: 'Exclusive 4x4 expedition through the 9.02 km Atal Tunnel to North Portal with snow gear provided.',
        start_time: '02:00 PM',
        end_time: '06:00 PM',
        cost: 9800,
        status: 'confirmed',
        location: 'Rohtang / Sissu, Lahaul Valley',
      },
      // Day 3 (Current Focus Day)
      {
        id: 'iti-1024-d3-1',
        trip_id: '1024',
        day_number: 3,
        order_index: 1,
        item_type: 'activity',
        title: 'Solang Valley Scenic Alpine Drive & Cable Car Gondola',
        description: 'Panoramic cable car ascent to Mount Phatru (3,200m) with sweeping views of the Pir Panjal ranges.',
        start_time: '10:00 AM',
        end_time: '01:00 PM',
        cost: 2800,
        status: 'confirmed',
        location: 'Solang Valley, Manali',
      },
      {
        id: 'iti-1024-d3-2',
        trip_id: '1024',
        day_number: 3,
        order_index: 2,
        item_type: 'meal',
        title: 'Gourmet Trout Lunch & Wood-Fired Pizza at Cafe 1947',
        description: 'Riverside dining by the roaring Manalsu stream in Old Manali.',
        start_time: '01:00 PM',
        end_time: '02:30 PM',
        cost: 3200,
        status: 'confirmed',
        location: 'Old Manali Bridge',
      },
      {
        id: 'iti-1024-d3-3',
        trip_id: '1024',
        day_number: 3,
        order_index: 3,
        item_type: 'activity',
        title: 'Solang Valley High Altitude Tandem Paragliding',
        description: 'High-thrill tandem paragliding from 8,000 ft launchpad with certified pilots and HD GoPro footage.',
        start_time: '03:00 PM',
        end_time: '05:30 PM',
        cost: 14000,
        status: 'confirmed', // will change to 'cancelled' when disruption is triggered
        location: 'Solang Valley Adventure Launchpad',
      },
      {
        id: 'iti-1024-d3-4',
        trip_id: '1024',
        day_number: 3,
        order_index: 4,
        item_type: 'leisure',
        title: 'Old Manali Bohemian Stroll & Cafe Lounge',
        description: 'Explore artisan leather shops, handmade silver jewelry, and live acoustic music cafes.',
        start_time: '06:00 PM',
        end_time: '08:00 PM',
        cost: 0,
        status: 'confirmed',
        location: 'Old Manali Village',
      },
      {
        id: 'iti-1024-d3-5',
        trip_id: '1024',
        day_number: 3,
        order_index: 5,
        item_type: 'hotel',
        title: 'Overnight Stay: The Himalayan Luxury Castle Resort',
        description: 'Complimentary herbal bedtime infusions and evening hearth fire.',
        start_time: '08:30 PM',
        end_time: '08:00 AM',
        cost: 23000,
        status: 'confirmed',
        location: 'Hadimba Road, Manali',
      },
      // Day 4
      {
        id: 'iti-1024-d4-1',
        trip_id: '1024',
        day_number: 4,
        order_index: 1,
        item_type: 'activity',
        title: 'Naggar Castle Heritage Tour & Roerich Russian Art Gallery',
        description: 'Visit the 500-year-old timber-bonded palace of the Kullu Rajas and Himalayan museum.',
        start_time: '10:00 AM',
        end_time: '02:00 PM',
        cost: 2400,
        status: 'confirmed',
        location: 'Naggar Heritage Village',
      },
      {
        id: 'iti-1024-d4-2',
        trip_id: '1024',
        day_number: 4,
        order_index: 2,
        item_type: 'activity',
        title: 'Artisan Cider Tasting & Mall Road Handloom Walk',
        description: 'Sample local organic Kullu apple wines and explore Himachali wool shawls.',
        start_time: '04:00 PM',
        end_time: '07:00 PM',
        cost: 1600,
        status: 'confirmed',
        location: 'Mall Road & Tibetan Market',
      },
      // Day 5
      {
        id: 'iti-1024-d5-1',
        trip_id: '1024',
        day_number: 5,
        order_index: 1,
        item_type: 'transport',
        title: 'Chauffeur Departure Transfer to Chandigarh Airport (IXC)',
        description: 'Comfortable downhill drive with lunch stopover at Pandoh Dam view deck.',
        start_time: '09:00 AM',
        end_time: '03:30 PM',
        cost: 8400,
        status: 'confirmed',
        location: 'Manali to Chandigarh',
      },
      {
        id: 'iti-1024-d5-2',
        trip_id: '1024',
        day_number: 5,
        order_index: 2,
        item_type: 'transport',
        title: 'IndiGo Flight 6E-519 (Chandigarh IXC → Mumbai BOM)',
        description: 'Evening return flight concluding the Manali Alpine Expedition.',
        start_time: '05:30 PM',
        end_time: '08:00 PM',
        cost: 22400,
        status: 'confirmed',
        location: 'Chandigarh to Mumbai',
      },
    ],
    bookings: [
      {
        id: 'bkg-1024-001',
        trip_id: '1024',
        vendor_id: 'vnd-ind-009',
        booking_reference: 'TF-FLT-9182',
        item_type: 'transport',
        amount: 58400,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-18T10:30:00Z',
      },
      {
        id: 'bkg-1024-002',
        trip_id: '1024',
        vendor_id: 'vnd-cab-006',
        booking_reference: 'TF-CAB-4401',
        item_type: 'transport',
        amount: 22400,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-18T10:35:00Z',
      },
      {
        id: 'bkg-1024-003',
        trip_id: '1024',
        vendor_id: 'vnd-him-001',
        booking_reference: 'TF-HTL-9912',
        item_type: 'hotel',
        amount: 92000,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-18T10:40:00Z',
      },
      {
        id: 'bkg-1024-act2',
        trip_id: '1024',
        vendor_id: 'vnd-sky-002',
        booking_reference: 'TF-ACT-8842',
        item_type: 'activity',
        amount: 14000,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-18T10:45:00Z',
      },
      {
        id: 'bkg-1024-005',
        trip_id: '1024',
        vendor_id: 'vnd-trk-005',
        booking_reference: 'TF-ACT-7711',
        item_type: 'activity',
        amount: 9800,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-18T10:50:00Z',
      },
      {
        id: 'bkg-1024-006',
        trip_id: '1024',
        vendor_id: 'vnd-trk-005',
        booking_reference: 'TF-GDE-3310',
        item_type: 'guide',
        amount: 5200,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-18T10:55:00Z',
      },
    ],
    alerts: [],
    notifications: [
      {
        id: 'notif-1024-1',
        trip_id: '1024',
        user_id: 'usr-rohan-sharma-001',
        title: 'Manali Tour #1024 Vouchers Issued',
        message: 'Himalayan Trails Operations has confirmed all airline tickets, resort reservations, and 4x4 chauffeur permits.',
        type: 'success',
        is_read: true,
        created_at: '2026-09-18T11:00:00Z',
      },
    ],
    change_history: [
      {
        id: 'chg-1024-0',
        trip_id: '1024',
        changed_by: 'operator',
        action: 'tour_confirmed',
        field_changed: 'status',
        old_value: 'planning',
        new_value: 'confirmed',
        reason: 'Himalayan Trails approved all allotments and verified mountain driving routes.',
        timestamp: '2026-09-18T11:00:00Z',
      },
    ],
    reviews: [],
  };

  // Demo trip 2: Delhi -> Goa (Attention / Flight delay)
  const goaTrip: Trip = {
    id: '1018',
    user_id: 'usr-priya-kapoor-002',
    destination_id: goaDest.id,
    title: 'Goa Coastal Sun & Heritage Mansions',
    status: 'ongoing',
    origin: 'Delhi',
    start_date: '2026-09-22',
    end_date: '2026-09-27',
    formatted_dates: 'Sep 22, 2026 – Sep 27, 2026',
    is_dates_confirmed: true,
    duration_days: 5,
    total_budget: 250000,
    total_cost: 245000,
    currency: 'INR',
    traveler_count: 6,
    travel_type: 'family',
    pace: 'relaxed',
    created_at: '2026-09-15T08:00:00Z',
    updated_at: new Date().toISOString(),
    destination: goaDest,
    preferences: {
      id: 'pref-1018',
      trip_id: '1018',
      budget_tier: 'luxury',
      interests: ['beaches', 'seafood', 'heritage', 'relaxation'],
      travel_companions: 'family',
      accommodation_types: ['luxury'],
      transport_preferences: ['flight', 'private_cab'],
      dietary_requirements: ['pescatarian'],
      created_at: '2026-09-15T08:00:00Z',
      updated_at: '2026-09-15T08:00:00Z',
    },
    itinerary: [
      {
        id: 'iti-1018-1',
        trip_id: '1018',
        day_number: 2,
        order_index: 1,
        item_type: 'activity',
        title: 'Private Catamaran Sunset Cruise on Mandovi River',
        cost: 18000,
        status: 'confirmed',
        location: 'Panjim Jetty',
      },
      {
        id: 'iti-1018-2',
        trip_id: '1018',
        day_number: 2,
        order_index: 2,
        item_type: 'hotel',
        title: 'Stay: Taj Exotica Resort & Spa Benaulim',
        cost: 120000,
        status: 'confirmed',
        location: 'South Goa',
      },
    ],
    bookings: [
      {
        id: 'bkg-1018-001',
        trip_id: '1018',
        vendor_id: 'vnd-taj-007',
        booking_reference: 'TF-HTL-7741',
        item_type: 'hotel',
        amount: 120000,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-15T09:00:00Z',
      },
    ],
    alerts: [
      {
        id: 'alt-1018-1',
        trip_id: '1018',
        alert_type: 'flight_delay',
        severity: 'warning',
        title: 'Inbound Flight 6E-204 Delayed by 45 Mins',
        description: 'Chauffeur pickup timing rescheduled to 17:15 at Dabolim Airport.',
        is_resolved: false,
        created_at: new Date().toISOString(),
      },
    ],
    notifications: [],
    change_history: [],
    reviews: [],
  };

  // Demo trip 3: Mumbai -> Kerala (Issue / Houseboat delay)
  const keralaTrip: Trip = {
    id: '1012',
    user_id: 'usr-vikram-singh-003',
    destination_id: 'dest-kerala-001',
    title: 'Kerala Backwaters & Munnar Tea Sanctuaries',
    status: 'ongoing',
    origin: 'Mumbai',
    start_date: '2026-09-20',
    end_date: '2026-09-26',
    formatted_dates: 'Sep 20, 2026 – Sep 26, 2026',
    is_dates_confirmed: true,
    duration_days: 6,
    total_budget: 320000,
    total_cost: 312000,
    currency: 'INR',
    traveler_count: 8,
    travel_type: 'family',
    pace: 'relaxed',
    created_at: '2026-09-12T11:00:00Z',
    updated_at: new Date().toISOString(),
    destination: {
      id: 'dest-kerala-001',
      name: 'Kerala Backwaters',
      slug: 'kerala-backwaters',
      country: 'India',
      state_region: 'Kerala',
      description: 'Serene palm-fringed lagoons, emerald tea hills of Munnar, and luxury traditional kettuvallam houseboats.',
      hero_image_url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
      tags: ['backwaters', 'nature', 'ayurveda', 'tea_gardens'],
      is_featured: true,
      created_at: '2026-09-01T00:00:00Z',
    },
    itinerary: [
      {
        id: 'iti-1012-1',
        trip_id: '1012',
        day_number: 4,
        order_index: 1,
        item_type: 'activity',
        title: 'Overnight Luxury 4-Bedroom Houseboat Cruise on Vembanad Lake',
        cost: 65000,
        status: 'confirmed',
        location: 'Kumarakom Jetty',
      },
    ],
    bookings: [
      {
        id: 'bkg-1012-001',
        trip_id: '1012',
        vendor_id: 'vnd-kum-008',
        booking_reference: 'TF-HB-5521',
        item_type: 'hotel',
        amount: 65000,
        currency: 'INR',
        status: 'confirmed',
        payment_status: 'paid',
        booking_date: '2026-09-12T12:00:00Z',
      },
    ],
    alerts: [
      {
        id: 'alt-1012-1',
        trip_id: '1012',
        alert_type: 'maintenance',
        severity: 'critical',
        title: 'Houseboat Kettuvallam Engine Inspection Required',
        description: 'Vessel docked for maintenance. Operator arranging VIP luxury reserve villa at Kumarakom Lake Resort.',
        is_resolved: false,
        created_at: new Date().toISOString(),
      },
    ],
    notifications: [],
    change_history: [],
    reviews: [],
  };

  // Demo trip 4: Kolkata -> Darjeeling (On Track)
  const darjeelingTrip: Trip = {
    id: '1030',
    user_id: 'usr-sourav-das-004',
    destination_id: darjeelingDest.id,
    title: 'Darjeeling Himalayan Vista & UNESCO Toy Train',
    status: 'ongoing',
    origin: 'Kolkata',
    start_date: '2026-09-23',
    end_date: '2026-09-28',
    formatted_dates: 'Sep 23, 2026 – Sep 28, 2026',
    is_dates_confirmed: true,
    duration_days: 5,
    total_budget: 160000,
    total_cost: 156000,
    currency: 'INR',
    traveler_count: 4,
    travel_type: 'family',
    pace: 'balanced',
    created_at: '2026-09-19T14:00:00Z',
    updated_at: new Date().toISOString(),
    destination: darjeelingDest,
    itinerary: [],
    bookings: [],
    alerts: [],
    notifications: [],
    change_history: [],
    reviews: [],
  };

  // Demo trip 5: Bangalore -> Rajasthan (New incoming request pending operator acceptance)
  const rajasthanRequestTrip: Trip = {
    id: '1035',
    user_id: 'usr-kavya-reddy-005',
    destination_id: 'dest-rajasthan-001',
    title: 'Royal Forts & Palaces of Jaipur & Udaipur',
    status: 'planning', // incoming request!
    origin: 'Bangalore',
    start_date: '2026-10-12',
    end_date: '2026-10-17',
    formatted_dates: 'Oct 12, 2026 – Oct 17, 2026',
    is_dates_confirmed: true,
    duration_days: 5,
    total_budget: 195000,
    total_cost: 182000,
    currency: 'INR',
    traveler_count: 2,
    travel_type: 'couple',
    pace: 'relaxed',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    destination: {
      id: 'dest-rajasthan-001',
      name: 'Jaipur & Udaipur, Rajasthan',
      slug: 'rajasthan-royal-heritage',
      country: 'India',
      state_region: 'Rajasthan',
      description: 'Grand Rajputana fortresses, serene Lake Pichola boat palaces, and authentic royal Rajasthani hospitality.',
      hero_image_url: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80',
      tags: ['heritage', 'palaces', 'culture', 'royal', 'photography'],
      is_featured: true,
      created_at: '2026-09-01T00:00:00Z',
    },
    preferences: {
      id: 'pref-1035',
      trip_id: '1035',
      budget_tier: 'luxury',
      interests: ['heritage', 'architecture', 'sunset_cruise', 'fine_dining'],
      travel_companions: 'couple',
      accommodation_types: ['heritage_haveli', 'palace'],
      transport_preferences: ['flight', 'chauffeur_sedan'],
      dietary_requirements: ['vegetarian'],
      special_requests: 'Anniversary celebration. Private romantic rooftop dinner overlooking Lake Palace requested.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    itinerary: [],
    bookings: [],
    alerts: [],
    notifications: [],
    change_history: [],
    reviews: [],
  };

  // Duplicate mainManaliTrip for trp-manali-alpine-demo-001 backward compatibility
  const demoAliasTrip: Trip = {
    ...mainManaliTrip,
    id: 'trp-manali-alpine-demo-001',
  };

  return [mainManaliTrip, goaTrip, keralaTrip, darjeelingTrip, rajasthanRequestTrip, demoAliasTrip];
}
