from backend.ai.gemini_service import GeminiService, gemini_service
from backend.ai.ai_types import (
    AIErrorCategory,
    AIProviderError,
    AIRequest,
    AIResponse,
    public_message_for,
)
from backend.ai.observability import (
    AI_LOGGER_NAME,
    format_cooldowns,
    get_ai_logger,
    log_attempt,
    log_attempt_failed,
    log_attempt_success,
    log_provider_attempt,
    log_provider_failed,
    log_provider_skipped,
    log_request_failed,
    log_request_started,
    new_request_id,
)
from backend.ai.errors import (
    FailoverAction,
    FailoverDirective,
    classify_exception,
    classify_http,
    directive_for,
    extract_status,
    new_error,
)
from backend.ai.providers import SUPPORTED_PROVIDERS, generate, get_adapter
from backend.ai.cascade import (
    cascade_provider,
    generate_via_gemini,
    generate_via_grok,
    generate_via_openrouter,
)
from backend.ai.router import PROVIDER_PRIORITY_ORDER, generate_with_failover
from backend.ai.health import (
    ErrorRecord,
    HealthManager,
    HealthStore,
    InMemoryHealthStore,
    ResourceState,
    ResourceStatus,
    key_scope,
    model_scope,
    provider_scope,
)

__all__ = [
    "GeminiService",
    "gemini_service",
    "AIErrorCategory",
    "AIProviderError",
    "AIRequest",
    "AIResponse",
    "public_message_for",
    "AI_LOGGER_NAME",
    "format_cooldowns",
    "get_ai_logger",
    "log_attempt",
    "log_attempt_failed",
    "log_attempt_success",
    "log_provider_attempt",
    "log_provider_failed",
    "log_provider_skipped",
    "log_request_failed",
    "log_request_started",
    "new_request_id",
    "FailoverAction",
    "FailoverDirective",
    "classify_exception",
    "classify_http",
    "directive_for",
    "extract_status",
    "new_error",
    "SUPPORTED_PROVIDERS",
    "generate",
    "get_adapter",
    "cascade_provider",
    "generate_via_gemini",
    "generate_via_grok",
    "generate_via_openrouter",
    "PROVIDER_PRIORITY_ORDER",
    "generate_with_failover",
    "ErrorRecord",
    "HealthManager",
    "HealthStore",
    "InMemoryHealthStore",
    "ResourceState",
    "ResourceStatus",
    "key_scope",
    "model_scope",
    "provider_scope",
]
